### ISSUE TITLE
adding WAF to the mix

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/IaC#21]
take I look on this  [link](https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/ag-overview) if we 're gonna use WAF or if we need it at the moment  , maybe  later , we are not in a rush .. you are ..😃  @Hack-Maze/security

**Comment by juba0x00** [comment]
# ياعم ملهاش لااازميية 


@Mostafa-ewida
